name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment variables in config.js
      run: |
        echo "window.env = {};" > config.js
        echo "window.env.EMAIL_USERNAME = '${{ secrets.EMAIL_USERNAME }}';" >> config.js
        echo "window.env.EMAIL_PASSWORD = '${{ secrets.EMAIL_PASSWORD }}';" >> config.js
        echo "window.env.EMAIL_TO = '${{ secrets.EMAIL_TO }}';" >> config.js
        echo "window.env.EMAIL_FROM = '${{ secrets.EMAIL_FROM }}';" >> config.js
      shell: bash

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build 
